### ISSUE TITLE
"Bad Gateway" Error

### ISSUE THREAD

**Issue by liz-luft** [seeq12/seeq-email-addon#8]
I recently installed the new email add-on and installed successfully. However, the emails are not sending. In the "_Job Results" folder, errors show "Bad Gateway"
![image](https://user-images.githubusercontent.com/97678941/221025007-a1d45c4e-0413-424f-8b10-761da0efecd8.png)

**Comment by cherrera2001** [comment]
It appears that the email service is not running on your system. If you have administrator access can you check the value of `Components/EmailerService/Enabled` within Admin\Configuration with the advanced flag?

**Comment by liz-luft** [comment]
Thanks for the quick response. You are correct in that I did not have that value set to True. However, after changing it, I still get the same result. Does the Seeq server need to be restarted or anything?

**Comment by cherrera2001** [comment]
Yes it would. Please file a ticket in our support portal https://seeq.atlassian.net/servicedesk/customer/portal/3 for assistance enabling the email service? Thanks!
