### ISSUE TITLE
Cron Expression in Schedule Parameter

### ISSUE THREAD

**Issue by liz-luft** [seeq12/seeq-email-addon#9]
What is the limitation in the cron expression syntax for the schedule parameter? The error says "provide a valid cron expression" but it doesn't appear to accept all cron expressions. I can't find a way to specify a time to offset the schedule such as every 8 hours starting at 6am.
![image](https://user-images.githubusercontent.com/97678941/222774735-344b5eda-3bc4-4549-889c-c1f039dcb454.png)
![image](https://user-images.githubusercontent.com/97678941/222774831-52cc9ff5-9635-4c37-ac23-de9f11b94c01.png)

**Comment by cherrera2001** [comment]
You are correct. This is an erroneous error message. Currently, the Schedule only supports expressions such as "Every x str". This is being addressed by #10.

**Comment by liz-luft** [comment]
Thanks Chris. If a user were to do every 8 hours, would it be based on when they scheduled it? For example, if I make the schedule at noon, would it run at noon, 8pm and 4am or would it run at 8am, 4pm and 12am?

**Comment by cherrera2001** [comment]
You are correct (rounded to the nearest 15 minutes). However, the open pull request will allow you to specify `0 0 8/7 ? * * *` which means `At second :00, at minute :00, every 7 hours starting at 08am, of every day`
